#Requires AutoHotkey v2.0

MsgBox "I went down to the local McDonalds"
MsgBox "But they didn't have any Jazzy Juice"
MsgBox "I sat down crying, with my dog"
MsgBox "But we continued on"
MsgBox "I ran 50 miles"
MsgBox "They all told me, you'll never find it"
MsgBox "The only thing you'll find is a knuckle sandwhich"
MsgBox "So I asked my friends, and I asked my wall"
MsgBox "Where is Jazzy Juice"

MsgBox "I turned around and saw it with my eyes"
MsgBox "And I ran faster than the sky"
MsgBox "I was almost in reach, of the juice"
MsgBox "But then my shoes were loose"
MsgBox "I had to tie them"
MsgBox "I looked up to see the juice being taken"
MsgBox "I caught up and caked him sending Jazzy Juice to the sky"
MsgBox "I planted my shoes down"
MsgBox "It's heading towards the ground"
MsgBox "And I caught Jazzy Juice"

MsgBox "But something started coursing through my veins"
MsgBox "My juice fell down and I didn't feel the same"
MsgBox "Moon fries looking kinda different what changed"
MsgBox "This song is going crazy it's about to go insane"
MsgBox "My brother lost a game of Fortnite and he let loose"
MsgBox "He got so mad he broke his legs and couldn't move"
MsgBox "Now all he wanted was good old Dr. Seuss"
MsgBox "But hey what's it matter we got Jazzy Juice"

MsgBox "I danced for hours with my drink, all damn day"
MsgBox "Bustin moves all the way"
MsgBox "I could not care less, about you"
MsgBox "Even my family knew"
MsgBox "I might be going crazy"
MsgBox "I thought maybe I should see my brother"
MsgBox "But I start to shudder at everything I've done"
MsgBox "The juice had taken me"
MsgBox "It took me so long to see"
MsgBox "I don't want Jazzy Juice"