Add-Type -AssemblyName PresentationFramework

[System.Windows.MessageBox]::Show("I went down to the local McDonalds")
[System.Windows.MessageBox]::Show("But they didn't have any Jazzy Juice")
[System.Windows.MessageBox]::Show("I sat down crying, with my dog")
[System.Windows.MessageBox]::Show("But we continued on")
[System.Windows.MessageBox]::Show("I ran 50 miles")
[System.Windows.MessageBox]::Show("They all told me, you'll never find it")
[System.Windows.MessageBox]::Show("The only thing you'll find is a knuckle sandwhich")
[System.Windows.MessageBox]::Show("So I asked my friends, and I asked my wall")
[System.Windows.MessageBox]::Show("Where is Jazzy Juice")

[System.Windows.MessageBox]::Show("I turned around and saw it with my eyes")
[System.Windows.MessageBox]::Show("And I ran faster than the sky")
[System.Windows.MessageBox]::Show("I was almost in reach, of the juice")
[System.Windows.MessageBox]::Show("But then my shoes were loose")
[System.Windows.MessageBox]::Show("I had to tie them")
[System.Windows.MessageBox]::Show("I looked up to see the juice being taken")
[System.Windows.MessageBox]::Show("I caught up and caked him sending Jazzy Juice to the sky")
[System.Windows.MessageBox]::Show("I planted my shoes down")
[System.Windows.MessageBox]::Show("It's heading towards the ground")
[System.Windows.MessageBox]::Show("And I caught Jazzy Juice")

[System.Windows.MessageBox]::Show("But something started coursing through my veins")
[System.Windows.MessageBox]::Show("My juice fell down and I didn't feel the same")
[System.Windows.MessageBox]::Show("Moon fries looking kinda different what changed")
[System.Windows.MessageBox]::Show("This song is going crazy it's about to go insane")
[System.Windows.MessageBox]::Show("My brother lost a game of Fortnite and he let loose")
[System.Windows.MessageBox]::Show("He got so mad he broke his legs and couldn't move")
[System.Windows.MessageBox]::Show("Now all he wanted was good old Dr. Seuss")
[System.Windows.MessageBox]::Show("But hey what's it matter we got Jazzy Juice")

[System.Windows.MessageBox]::Show("I danced for hours with my drink, all damn day")
[System.Windows.MessageBox]::Show("Bustin moves all the way")
[System.Windows.MessageBox]::Show("I could not care less, about you")
[System.Windows.MessageBox]::Show("Even my family knew")
[System.Windows.MessageBox]::Show("I might be going crazy")
[System.Windows.MessageBox]::Show("I thought maybe I should see my brother")
[System.Windows.MessageBox]::Show("But I start to shudder at everything I've done")
[System.Windows.MessageBox]::Show("The juice had taken me")
[System.Windows.MessageBox]::Show("It took me so long to see")
[System.Windows.MessageBox]::Show("I don't want Jazzy Juice")